'use client';

import Image from 'next/image';
import { FormEvent, useEffect, useMemo, useState } from 'react';

type Profile = { name:string; email:string; birth:string; time:string; city:string };
type Account = { passwordHash:string; profile:Profile };
type Accounts = Record<string, Account>;
type Reading = { id:string; createdAt:string; question:string; cards:string[] };
type View = 'today'|'week'|'nextweek'|'month'|'nextmonth'|'history';

type Card = { name:string; numeral:string; symbol:string; upright:string; reversed:string; theme:string };
const cards: Card[] = [
{name:'El Loco',numeral:'0',symbol:'✧',theme:'Inicio',upright:'Atrévete a comenzar con curiosidad y margen para sorprenderte.',reversed:'Antes de saltar, revisa qué detalle estás dejando fuera.'},
{name:'El Mago',numeral:'I',symbol:'✦',theme:'Iniciativa',upright:'Tienes recursos suficientes para dar el primer paso.',reversed:'Ordena tus recursos antes de intentar controlar el resultado.'},
{name:'La Sacerdotisa',numeral:'II',symbol:'☾',theme:'Intuición',upright:'La información que falta aparecerá si haces espacio para escuchar.',reversed:'No confundas ansiedad con intuición; espera una señal más clara.'},
{name:'La Emperatriz',numeral:'III',symbol:'❀',theme:'Crecimiento',upright:'Nutre lo que ya está creciendo y dale tiempo.',reversed:'Cuida tu energía antes de seguir entregándola hacia afuera.'},
{name:'El Emperador',numeral:'IV',symbol:'♜',theme:'Estructura',upright:'Un límite claro puede darte más libertad de la que imaginas.',reversed:'Evita rigidizar una situación que necesita adaptación.'},
{name:'El Hierofante',numeral:'V',symbol:'◇',theme:'Sentido',upright:'Vuelve a tus valores y decide desde lo esencial.',reversed:'Cuestiona una regla que ya no representa lo que necesitas.'},
{name:'Los Enamorados',numeral:'VI',symbol:'♡',theme:'Elección',upright:'Elige aquello que alinea deseo, valores y acción.',reversed:'Una decisión pide honestidad antes que comodidad.'},
{name:'El Carro',numeral:'VII',symbol:'➶',theme:'Avance',upright:'El movimiento favorece tu objetivo si mantienes dirección.',reversed:'Avanzar más rápido no sirve si el rumbo aún no está claro.'},
{name:'La Fuerza',numeral:'VIII',symbol:'∞',theme:'Templanza',upright:'La suavidad será más eficaz que la presión.',reversed:'No gastes energía demostrando algo que ya sabes de ti.'},
{name:'El Ermitaño',numeral:'IX',symbol:'✷',theme:'Claridad',upright:'Una pausa consciente puede mostrarte la respuesta correcta.',reversed:'No te aísles por demasiado tiempo de quienes pueden ayudarte.'},
{name:'La Rueda',numeral:'X',symbol:'◉',theme:'Cambio',upright:'Una coincidencia abre una alternativa; muévete con el giro.',reversed:'No todo retraso es un bloqueo; puede ser una corrección de rumbo.'},
{name:'La Justicia',numeral:'XI',symbol:'⚖',theme:'Balance',upright:'Mira hechos y consecuencias antes de decidir.',reversed:'Revisa si estás siendo más exigente contigo que con los demás.'},
{name:'El Colgado',numeral:'XII',symbol:'▽',theme:'Perspectiva',upright:'Cambiar el ángulo puede resolver lo que la fuerza no resolvió.',reversed:'Una espera pierde sentido si solo posterga una decisión.'},
{name:'La Muerte',numeral:'XIII',symbol:'✢',theme:'Transformación',upright:'Cerrar una etapa libera energía para una nueva forma.',reversed:'Soltar gradualmente también cuenta como transformación.'},
{name:'La Templanza',numeral:'XIV',symbol:'≈',theme:'Integración',upright:'Combina lo mejor de dos caminos en lugar de elegir extremos.',reversed:'Baja el ritmo; el equilibrio necesita ajustes pequeños.'},
{name:'El Diablo',numeral:'XV',symbol:'♢',theme:'Apego',upright:'Observa qué deseo está tomando demasiado espacio.',reversed:'Ya estás viendo con claridad un patrón que puedes cambiar.'},
{name:'La Torre',numeral:'XVI',symbol:'⚡',theme:'Reorden',upright:'Una estructura inestable pide una corrección honesta.',reversed:'Puedes prevenir un quiebre mayor atendiendo señales pequeñas.'},
{name:'La Estrella',numeral:'XVII',symbol:'✦',theme:'Confianza',upright:'Recuperas claridad; una ruta posible empieza a mostrarse.',reversed:'La esperanza necesita una acción concreta para sostenerse.'},
{name:'La Luna',numeral:'XVIII',symbol:'☽',theme:'Sensibilidad',upright:'No decidas desde la primera impresión; observa un poco más.',reversed:'Una confusión comienza a aclararse si preguntas directamente.'},
{name:'El Sol',numeral:'XIX',symbol:'☼',theme:'Expansión',upright:'Tu energía favorece mostrar y compartir lo que has construido.',reversed:'No necesitas estar al máximo para reconocer un buen avance.'},
{name:'El Juicio',numeral:'XX',symbol:'✺',theme:'Llamado',upright:'Una decisión pendiente vuelve con mayor claridad.',reversed:'Antes de juzgar el pasado, identifica qué aprendiste de él.'},
{name:'El Mundo',numeral:'XXI',symbol:'⊕',theme:'Cierre',upright:'Una etapa se integra; reconoce lo aprendido antes de avanzar.',reversed:'Termina el último detalle para sentir realmente el cierre.'}
];

const zodiacSigns = ['Capricornio','Acuario','Piscis','Aries','Tauro','Géminis','Cáncer','Leo','Virgo','Libra','Escorpio','Sagitario'];
const zodiacEnds = [19,18,20,19,20,20,22,22,22,22,21,21];
const zodiacTone: Record<string,string> = {
Aries:'iniciativa y franqueza',Tauro:'estabilidad y construcción',Géminis:'curiosidad y conversación',Cáncer:'cuidado y pertenencia',Leo:'expresión y confianza',Virgo:'orden y mejora',Libra:'vínculos y equilibrio',Escorpio:'profundidad y transformación',Sagitario:'expansión y aprendizaje',Capricornio:'estructura y propósito',Acuario:'innovación y perspectiva',Piscis:'sensibilidad e intuición'
};

function hash(value:string){ let h=2166136261; for(const c of value){h^=c.charCodeAt(0);h=Math.imul(h,16777619)} return h>>>0; }
function reduceNumber(n:number){ while(n>9 && ![11,22,33].includes(n)) n=String(n).split('').reduce((a,b)=>a+Number(b),0); return n; }
function lifePath(date:string){ return reduceNumber(date.replace(/\D/g,'').split('').reduce((a,b)=>a+Number(b),0)); }
function birthdayNumber(date:string){ return date ? reduceNumber(Number(date.split('-')[2])) : 0; }
function personalYear(date:string, when:Date){ if(!date)return 0; const [,m,d]=date.split('-').map(Number); return reduceNumber(m+d+when.getFullYear()); }
function personalMonth(date:string, when:Date){ return reduceNumber(personalYear(date,when)+when.getMonth()+1); }
function personalDay(date:string, when:Date){ return reduceNumber(personalMonth(date,when)+when.getDate()); }
function zodiac(date:string){ if(!date)return '—'; const [,m,d]=date.split('-').map(Number); return d<=zodiacEnds[m-1]?zodiacSigns[m-1]:zodiacSigns[m%12]; }
function isoLocal(d:Date){ const x=new Date(d.getTime()-d.getTimezoneOffset()*60000); return x.toISOString().slice(0,10); }
function mondayOf(date:Date){ const d=new Date(date); const day=d.getDay()||7; d.setHours(12,0,0,0); d.setDate(d.getDate()-day+1); return d; }
function addDays(d:Date,n:number){ const x=new Date(d); x.setDate(x.getDate()+n); return x; }
function monthName(d:Date){ return new Intl.DateTimeFormat('es-CL',{month:'long',year:'numeric'}).format(d); }
async function sha256(text:string){ const bytes=new TextEncoder().encode(text); const digest=await crypto.subtle.digest('SHA-256',bytes); return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
function loadAccounts():Accounts{ try{return JSON.parse(localStorage.getItem('ecotarot-accounts')||'{}')}catch{return {}} }
function saveAccounts(v:Accounts){ localStorage.setItem('ecotarot-accounts',JSON.stringify(v)); }
function getHistory(email:string):Reading[]{ try{return JSON.parse(localStorage.getItem(`ecotarot-history:${email}`)||'[]')}catch{return []} }
function saveHistory(email:string,v:Reading[]){ localStorage.setItem(`ecotarot-history:${email}`,JSON.stringify(v.slice(0,50))); }
function cardFor(seed:string){ const h=hash(seed); return { card:cards[h%cards.length], reversed:(h>>>8)%4===0 }; }
function meaning(seed:string){ const x=cardFor(seed); return { ...x, text:x.reversed?x.card.reversed:x.card.upright }; }
function themeFor(n:number){ const themes:Record<number,string>={1:'iniciar y tomar iniciativa',2:'cooperar y escuchar',3:'expresarte y crear',4:'ordenar y construir',5:'cambiar y explorar',6:'cuidar vínculos y responsabilidades',7:'observar y profundizar',8:'materializar con criterio',9:'cerrar, depurar y compartir',11:'confiar en tu intuición',22:'construir algo de largo alcance',33:'servir desde la experiencia'}; return themes[n]||'mantener presencia y flexibilidad'; }

export default function EcoTarotApp(){
 const [session,setSession]=useState<string|null>(null); const [profile,setProfile]=useState<Profile|null>(null); const [authOpen,setAuthOpen]=useState(false); const [authMode,setAuthMode]=useState<'login'|'register'>('register'); const [profileOpen,setProfileOpen]=useState(false); const [view,setView]=useState<View>('today'); const [authError,setAuthError]=useState(''); const [question,setQuestion]=useState(''); const [spread,setSpread]=useState<1|3>(1); const [customCards,setCustomCards]=useState<{card:Card;reversed:boolean}[]>([]); const [history,setHistory]=useState<Reading[]>([]);
 useEffect(()=>{ const email=localStorage.getItem('ecotarot-session'); if(email){const a=loadAccounts()[email]; if(a){setSession(email);setProfile(a.profile);setHistory(getHistory(email));}} },[]);
 const now=useMemo(()=>new Date(),[]); const todayKey=isoLocal(now); const lp=profile?lifePath(profile.birth):7; const bday=profile?birthdayNumber(profile.birth):0; const py=profile?personalYear(profile.birth,now):0; const pm=profile?personalMonth(profile.birth,now):0; const pd=profile?personalDay(profile.birth,now):0; const sign=profile?zodiac(profile.birth):'—'; const daily=meaning(`${session||'visit'}:${todayKey}`);
 const weekStart=mondayOf(now); const nextWeek=addDays(weekStart,7); const nextMonth=new Date(now.getFullYear(),now.getMonth()+1,1);
 const dateLabel=new Intl.DateTimeFormat('es-CL',{weekday:'long',day:'numeric',month:'long'}).format(now);
 const firstName=profile?.name.trim().split(/\s+/)[0];
 const convergence = profile ? `Tu día personal ${pd} favorece ${themeFor(pd)}. ${sign} aporta ${zodiacTone[sign]||'perspectiva personal'} y ${daily.card.name} pone el foco en ${daily.card.theme.toLowerCase()}.` : 'Crea tu perfil para combinar tu numerología, tu signo solar y tu tarot diario en una sola lectura.';

 async function submitAuth(e:FormEvent<HTMLFormElement>){ e.preventDefault(); setAuthError(''); const f=new FormData(e.currentTarget); const email=String(f.get('email')).trim().toLowerCase(); const password=String(f.get('password')); if(password.length<4){setAuthError('La clave debe tener al menos 4 caracteres.');return;} const accounts=loadAccounts(); const digest=await sha256(password); if(authMode==='login'){ if(!accounts[email]||accounts[email].passwordHash!==digest){setAuthError('Correo o clave incorrectos.');return;} localStorage.setItem('ecotarot-session',email); setSession(email);setProfile(accounts[email].profile);setHistory(getHistory(email));setAuthOpen(false);return; } if(accounts[email]){setAuthError('Ese correo ya tiene una cuenta. Inicia sesión.');return;} const empty:Profile={name:'',email,birth:'',time:'',city:''}; accounts[email]={passwordHash:digest,profile:empty};saveAccounts(accounts);localStorage.setItem('ecotarot-session',email);setSession(email);setProfile(empty);setAuthOpen(false);setProfileOpen(true); }
 function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault(); if(!session)return; const f=new FormData(e.currentTarget); const p:Profile={name:String(f.get('name')).trim(),email:session,birth:String(f.get('birth')),time:String(f.get('time')),city:String(f.get('city')).trim()}; const accounts=loadAccounts(); if(accounts[session]){accounts[session].profile=p;saveAccounts(accounts);}setProfile(p);setProfileOpen(false);}
 function logout(){ localStorage.removeItem('ecotarot-session');setSession(null);setProfile(null);setHistory([]);setView('today'); }
 function requireAccount(){ if(!session){setAuthMode('register');setAuthOpen(true);return false;} if(!profile?.birth){setProfileOpen(true);return false;} return true; }
 function drawCustom(){ if(!requireAccount())return; const base=`${session}:${Date.now()}:${question}`; const list=Array.from({length:spread},(_,i)=>cardFor(`${base}:${i}`)); setCustomCards(list); const reading:Reading={id:String(Date.now()),createdAt:new Date().toISOString(),question:question.trim()||'Lectura abierta',cards:list.map(x=>`${x.card.name}${x.reversed?' · invertida':''}`)}; const next=[reading,...history];setHistory(next);saveHistory(session!,next); }
 function openProfile(){ if(!session){setAuthMode('register');setAuthOpen(true)}else setProfileOpen(true); }
 const days=(start:Date)=>Array.from({length:7},(_,i)=>{const d=addDays(start,i);const num=profile?personalDay(profile.birth,d):0;const c=meaning(`${session}:${isoLocal(d)}`);return {d,num,c};});
 const monthCards=(d:Date)=>{const num=profile?personalMonth(profile.birth,d):0;const c=meaning(`${session}:${d.getFullYear()}-${d.getMonth()+1}`);return {num,c};};

 return <main>
  <nav><a className="brand" href="#inicio"><span>◐</span> ECOTAROT</a><div className="navlinks"><a href="#lectura">Hoy</a><a href="#oraculo">Tarot</a><a href="#mapa">Pronóstico</a></div><div className="navActions">{session&&<button className="navText" onClick={logout}>Salir</button>}<button className="profile" onClick={openProfile}>{session?(firstName||'Mi perfil'):'Ingresar'} <span>→</span></button></div></nav>

  <section id="inicio" className="hero"><Image src="/ecotarot-hero.webp" alt="Cartas de tarot bajo un cielo nocturno" fill priority sizes="100vw"/><div className="veil"/><div className="heroCopy"><div className="eyebrow">✦ NUMEROLOGÍA · ASTROLOGÍA · TAROT</div><h1>{firstName?`${firstName}, mira tu momento.`:'Tu mapa. Tu momento.'}<br/><em>Una lectura, tres señales.</em></h1><p>EcoTarot combina tu fecha de nacimiento, tu signo solar y un tarot persistente para entregarte una guía diaria, semanal y mensual coherente.</p><div className="actions"><button className="primary" onClick={()=>{requireAccount();document.querySelector('#lectura')?.scrollIntoView({behavior:'smooth'})}}>Ver mi lectura <span>✦</span></button><button className="ghost" onClick={openProfile}>{session?'Editar mi perfil':'Crear cuenta gratis'}</button></div><small>Herramienta simbólica y reflexiva. No reemplaza consejo médico, legal o financiero.</small></div><div className="scroll">DESCUBRE TU MENSAJE <i>↓</i></div></section>

  <section id="lectura" className="reading wrap"><div className="sectionHead"><div><span className="kicker">TU LECTURA DE HOY</span><h2>{firstName?`Buenos días, ${firstName}`:'Tu energía del día'}</h2></div><p>{dateLabel.charAt(0).toUpperCase()+dateLabel.slice(1)} · actualizado según tu hora local</p></div>
   {!profile?.birth?<div className="emptyState"><span>✦</span><h3>Completa tu mapa personal</h3><p>Con tu nombre, fecha, hora y lugar de nacimiento podemos personalizar tus ciclos y conservar tus lecturas.</p><button className="primary" onClick={openProfile}>Crear mi mapa</button></div>:
   <><div className="insightGrid"><article className="mainInsight"><div className="orbit">{daily.card.symbol}<i>✦</i></div><div><span className="kicker">CONVERGENCIA DEL DÍA</span><h3>{daily.card.theme} + día {pd}</h3><p>{convergence}</p><div className="chips"><b>Camino <span>{lp}</span></b><b>Año personal <span>{py}</span></b><b>Mes personal <span>{pm}</span></b></div></div></article><article className="mini"><span className="icon">☉</span><small>SIGNO SOLAR</small><h3>{sign}</h3><p>Tu base natal enfatiza {zodiacTone[sign]||'tu forma personal de avanzar'}.</p></article><article className="mini"><span className="icon">№</span><small>NUMEROLOGÍA</small><h3>Día {pd}</h3><p>El foco de hoy es {themeFor(pd)}.</p></article></div>
   <div className="dailyMessage"><div><span className="kicker">CARTA DEL DÍA · {daily.reversed?'INVERTIDA':'DERECHA'}</span><h3>{daily.card.name}</h3><p>{daily.text}</p></div><div className="dailyNumber"><small>CAMINO DE VIDA</small><strong>{lp}</strong><span>Nacimiento {bday}</span></div></div></>}
  </section>

  <section id="oraculo" className="oracle"><div className="wrap"><div className="sectionHead light"><div><span className="kicker">PREGÚNTALE A ECOTAROT</span><h2>Tarot del momento</h2></div><p>Formula una pregunta abierta. Las cartas se guardan en tu historial para que la lectura no desaparezca.</p></div><div className="askBox"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="¿Qué debería considerar sobre esta situación?"/><div className="spreadButtons"><button className={spread===1?'selected':''} onClick={()=>setSpread(1)}>1 carta</button><button className={spread===3?'selected':''} onClick={()=>setSpread(3)}>3 cartas</button><button className="primary" onClick={drawCustom}>Revelar lectura ✦</button></div></div>
   <div className={`customSpread spread${customCards.length}`}>{customCards.map((x,i)=><article className="revealedCard" key={`${x.card.name}-${i}`}><div className="cardFace"><small>{x.card.numeral}</small><strong>{x.card.symbol}</strong><span>{x.card.name}</span></div><div><span className="kicker">{spread===3?['SITUACIÓN','INFLUENCIA','TENDENCIA'][i]:'MENSAJE'}</span><h3>{x.card.theme}</h3><p>{x.reversed?x.card.reversed:x.card.upright}</p><small>{x.reversed?'Carta invertida':'Carta derecha'}</small></div></article>)}</div>
  </div></section>

  <section id="mapa" className="forecast wrap"><div className="sectionHead"><div><span className="kicker">TU BRÚJULA PERSONAL</span><h2>Hoy, semanas y meses</h2></div><div className="viewTabs"><button className={view==='today'?'active':''} onClick={()=>setView('today')}>Hoy</button><button className={view==='week'?'active':''} onClick={()=>setView('week')}>Semana</button><button className={view==='nextweek'?'active':''} onClick={()=>setView('nextweek')}>Próxima</button><button className={view==='month'?'active':''} onClick={()=>setView('month')}>Mes</button><button className={view==='nextmonth'?'active':''} onClick={()=>setView('nextmonth')}>Próx. mes</button><button className={view==='history'?'active':''} onClick={()=>setView('history')}>Historial</button></div></div>
   {!profile?.birth?<div className="emptyState compact"><p>Inicia sesión y completa tu perfil para ver pronósticos personales.</p><button className="outline dark" onClick={openProfile}>Configurar perfil</button></div>:view==='week'||view==='nextweek'?<WeekView data={days(view==='week'?weekStart:nextWeek)} />:view==='month'||view==='nextmonth'?<MonthView data={monthCards(view==='month'?now:nextMonth)} date={view==='month'?now:nextMonth}/>:view==='history'?<HistoryView history={history}/>:<TodayView pd={pd} sign={sign} card={daily.card} text={daily.text}/>} 
  </section>

  <footer><a className="brand" href="#inicio"><span>◐</span> ECOTAROT</a><p>Numerología + signo solar + tarot, integrados en una sola brújula.</p><p>© {new Date().getFullYear()} EcoTarot · Lecturas orientativas.</p></footer>

  {authOpen&&<div className="modal" onMouseDown={e=>{if(e.target===e.currentTarget)setAuthOpen(false)}}><form onSubmit={submitAuth}><button type="button" className="close" onClick={()=>setAuthOpen(false)}>×</button><span className="kicker">{authMode==='login'?'BIENVENIDO DE NUEVO':'CREA TU CUENTA'}</span><h2>{authMode==='login'?'Entrar a EcoTarot':'Guarda tu mapa'}</h2><p>Usa tu correo y una clave simple de al menos 4 caracteres.</p><label>Correo<input required type="email" name="email" autoComplete="email"/></label><label>Clave<input required minLength={4} type="password" name="password" autoComplete={authMode==='login'?'current-password':'new-password'}/></label>{authError&&<div className="formError">{authError}</div>}<button className="primary wide" type="submit">{authMode==='login'?'Entrar':'Crear cuenta'} <span>✦</span></button><button className="switchMode" type="button" onClick={()=>{setAuthError('');setAuthMode(authMode==='login'?'register':'login')}}>{authMode==='login'?'No tengo cuenta · Registrarme':'Ya tengo cuenta · Ingresar'}</button><small>En esta versión tus credenciales se protegen con hash y permanecen en este dispositivo.</small></form></div>}
  {profileOpen&&session&&<div className="modal" onMouseDown={e=>{if(e.target===e.currentTarget&&profile?.birth)setProfileOpen(false)}}><form onSubmit={saveProfile}><button type="button" className="close" onClick={()=>profile?.birth&&setProfileOpen(false)}>×</button><span className="kicker">TU MAPA PERSONAL</span><h2>Datos de nacimiento</h2><p>La hora se guarda para una futura carta astral completa. Esta versión usa tu signo solar y no inventa ascendente ni casas.</p><label>Nombre completo<input required name="name" defaultValue={profile?.name}/></label><div className="row"><label>Fecha de nacimiento<input required type="date" name="birth" defaultValue={profile?.birth}/></label><label>Hora de nacimiento<input type="time" name="time" defaultValue={profile?.time}/></label></div><label>Ciudad de nacimiento<input required name="city" placeholder="Santiago, Chile" defaultValue={profile?.city}/></label><button className="primary wide" type="submit">Guardar mi mapa <span>✦</span></button><small>EcoTarot no presenta estas lecturas como predicciones científicamente validadas.</small></form></div>}
 </main>
}

function TodayView({pd,sign,card,text}:{pd:number;sign:string;card:Card;text:string}){const items=[['Amor y vínculos','Habla desde la calma','La escucha sincera será más útil que tratar de adivinar lo que el otro piensa.'],['Trabajo y propósito','Prioriza lo esencial',`Tu día ${pd} favorece ${themeFor(pd)}. Evita repartir tu energía en demasiados frentes.`],['Bienestar','Cuida tu ritmo',`${sign} puede beneficiarse hoy de una pausa antes de reaccionar. ${card.name} refuerza esa idea.`]];return <div className="forecastGrid">{items.map((x,i)=><article key={x[0]}><span>{['♡','✦','☼'][i]}</span><small>{x[0].toUpperCase()}</small><h3>{x[1]}</h3><p>{x[2]}</p><b>{text}</b></article>)}</div>}
function WeekView({data}:{data:{d:Date;num:number;c:ReturnType<typeof meaning>}[]}){return <div className="weekGrid">{data.map(({d,num,c})=><article key={d.toISOString()}><small>{new Intl.DateTimeFormat('es-CL',{weekday:'short'}).format(d).toUpperCase()}</small><strong>{d.getDate()}</strong><span>Día {num}</span><h3>{c.card.theme}</h3><p>{c.text}</p></article>)}</div>}
function MonthView({data,date}:{data:{num:number;c:ReturnType<typeof meaning>};date:Date}){return <div className="monthPanel"><div className="monthOrb"><small>MES PERSONAL</small><strong>{data.num}</strong></div><div><span className="kicker">{monthName(date).toUpperCase()}</span><h3>{data.c.card.name} · {data.c.card.theme}</h3><p>Tu mes personal {data.num} favorece {themeFor(data.num)}. La carta guía sugiere: {data.c.text}</p><div className="monthNotes"><b>Oportunidad</b><span>Concentrar energía en una prioridad concreta.</span><b>Atención</b><span>No convertir una tendencia simbólica en una decisión automática.</span></div></div></div>}
function HistoryView({history}:{history:Reading[]}){if(!history.length)return <div className="emptyState compact"><span>☾</span><h3>Aún no tienes consultas guardadas</h3><p>Haz una tirada de 1 o 3 cartas y aparecerá aquí.</p></div>;return <div className="historyList">{history.map(r=><article key={r.id}><div><small>{new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(new Date(r.createdAt))}</small><h3>{r.question}</h3></div><p>{r.cards.join(' · ')}</p></article>)}</div>}
